aliases:
    fleeks: cd ~/.local/share/fleek
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - emacs
    - aria
    - yt-dlp
    - ytmdl
    - jetbrains.pycharm-community
    - gitkraken
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: david-laptop
      os: linux
      username: dlafreniere
track: nixos-unstable
unfree: true
users:
    - email: dlafreniere349@gmail.com
      name: David LaFreniere
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: dlafreniere
